version: '3'

services:
   apache:
    image: my-laravel-image
    build:  ./
    volumes:
      - ./:/app
    ports:
      - 8000:8000
   nginx:
    image: nginx:1.11
    ports:
      - 27:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx:/data/nginx/
      - ./nginx/files:/var/www/files/
   db:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
   adminer:
     image: adminer
     ports:
      - 8080:8080
   redis:
     image: redis
     volumes:
       - ./redis/sessions/redis.conf:/usr/local/etc/redis/redis.conf
     ports:
      - 6379:6379


